# Generated by Django 3.0.8 on 2020-07-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150)),
                ('college_short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_name1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150)),
                ('department_short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField()),
                ('level_name', models.CharField(max_length=50)),
                ('level_semester', models.CharField(choices=[('1ST SEMESTER', '1st Sem'), ('2ND SEMESTER', '2nd Sem'), ('SUMMER', 'Summer')], max_length=50)),
                ('level_note', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospectus_name', models.CharField(max_length=250)),
                ('prospectus_note', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_no', models.CharField(max_length=50)),
                ('descriptive_title', models.CharField(max_length=250)),
                ('lecture', models.FloatField()),
                ('laboratory', models.FloatField()),
                ('credit', models.FloatField()),
                ('pre1', models.CharField(max_length=50)),
                ('pre2', models.CharField(max_length=50)),
                ('pre3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=11)),
                ('qr_code', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('name_ext', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREBULAR', 'Irregualr'), ('OVER STAYING', 'Over Staying'), ('OTHERS', 'Others')], max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='regz.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='ProSubects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prolevels', to='regz.Levels')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosubjects', to='regz.Subjects')),
            ],
        ),
    ]
