# Generated by Django 3.0.8 on 2020-07-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procourses', to='regz.Courses'),
            preserve_default=False,
        ),
    ]
